
name: Predictive Maintenance ML Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.10"}
      - name: Install deps
        run: pip install -r requirements.txt huggingface_hub
      - name: Deploy to HF Spaces
        run: |
          python -c "
          from huggingface_hub import HfApi; import os
          api = HfApi(token=os.environ['HF_TOKEN'])
          api.upload_folder(repo_id='Divyap90/predict', repo_type='space', folder_path='.')
          "
